export const brands = [
    {
        image:'/assets/images/logos/milenio.png',
        background:'#fff'
    },
    {
        image:'/assets/images/logos/chic.png',
        background:'#fff'
    },
    {
        image:'/assets/images/logos/telediario.png',
        background:'#000'
    },
    {
        image:'/assets/images/logos/canal-6.png',
        background:'#fbce01'
    },
    {
        image:'/assets/images/logos/fama.png',
        background:'#fff'
    },
    {
        image:'/assets/images/logos/septima.png',
        background:'#0b455c'
    },
    {
        image:'/assets/images/logos/mediotiempo.png',
        background:'#fff'
    },
    {
        image:'/assets/images/logos/m.png',
        background:'#fff'
    },
    {
        image:'/assets/images/logos/la-aficion.jpg',
        background:'#4ea748'
    }
]